export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS'
export const CUSTOMER_REGISTER_FAIL = 'CUSTOMER_REGISTER_FAIL'

export const ADMIN_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS'
export const ADMIN_REGISTER_FAIL = 'CUSTOMER_REGISTER_FAIL'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const USER_LOADED = 'USER_LOADED'
export const CHEF_REGISTER_SUCCESS = 'CHEF_REGISTER_SUCCESS'
export const CHEF_REGISTER_FAIL = 'CHEF_REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const HISTORY_RECOMMENDATION_SUCCESS = 'HISTORY_RECOMMENDATION_SUCCESS'
export const HISTORY_RECOMMENDATION_FAIL = 'HISTORY_RECOMMENDATION_FAIL'

export const CHEF_EDITPROFILE_SUCCESS = 'CHEF_EDITPROFILE_SUCCESS'
export const CHEF_EDITPROFILE_FAIL = 'CHEF_EDITPROFILE_FAIL'
export const CHEF_PASSCHANGE_SUCCESS = 'CHEF_PASSCHANGE_SUCCESS'
export const CHEF_PASSCHANGE_FAIL = 'CHEF_PASSCHANGE_FAIL'

export const CUSTOMER_EDITPROFILE_SUCCESS = 'CUSTOMER_EDITPROFILE_SUCCESS'
export const CUSTOMER_EDITPROFILE_FAIL = 'CUSTOMER_EDITPROFILE_FAIL'
export const CUSTOMER_PASSCHANGE_SUCCESS = 'CUSTOMER_PASSCHANGE_SUCCESS'
export const CUSTOMER_PASSCHANGE_FAIL = 'CUSTOMER_PASSCHANGE_FAIL'


export const POPULAR_KITCHENS_SUCCESS = 'POPULAR_KITCHENS_SUCCESS'
export const POPULAR_KITCHENS_FAIL = 'POPULAR_KITCHENS_FAIL'

export const LOGOUT = 'LOGOUT'
export const ACTIVE_ORDERS_CHEF_SUCCESS = 'ACTIVE_ORDERS_CHEF_SUCCESS'
export const ACTIVE_ORDERS_CHEF_FAIL = 'ACTIVE_ORDERS_CHEF_FAIL'

export const COMPLETE_ORDERS_CHEF_SUCCESS = 'COMPLETE_ORDERS_CHEF_SUCCESS'
export const COMPLETE_ORDERS_CHEF_FAIL = 'COMPLETE_ORDERS_CHEF_FAIL'

export const ACTIVE_ORDERS_CUSTOMER_SUCCESS = 'ACTIVE_ORDERS_CUSTOMER_SUCCESS'
export const ACTIVE_ORDERS_CUSTOMER_FAIL = 'ACTIVE_ORDERS_CUSTOMER_FAIL'

export const COMPLETE_ORDERS_CUSTOMER_SUCCESS = 'COMPLETE_ORDERS_CUSTOMER_SUCCESS'
export const COMPLETE_ORDERS_CUSTOMER_FAIL = 'COMPLETE_ORDERS_CUSTOMER_FAIL'
export const ADD_CART = 'ADD_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const CHECKOUT_FAIL = "CHECKOUT_FAIL"
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS"


export const DISH_ADDED_SUCCESSFULLY = "DISH_ADDED_SUCCESSFULLY"
export const FAILED_TO_ADD_DISH = "FAILED_TO_ADD_DISH"

export const DISH_EDITED_SUCCESSFULLY = "DISH_EDITED_SUCCESSFULLY"
export const FAILED_TO_EDIT_DISH = "FAILED_TO_EDIT_DISH"

export const SET_QUERY = 'SET_QUERY'
export const SET_PAGENUMBER = 'SET_PAGENUMBER'

export const CHEF_ANALYTICS_SUCCESS = 'CHEF_ANALYTICS_SUCCESS'
export const CHEF_ANALYTICS_FAIL = 'CHEF_ANALYTICS_FAIL'
export const CHEF_OWN_DETAILS_SUCCESS = 'CHEF_OWN_DETAILS_SUCCESS'
export const CHEF_OWN_DETAILS_FAIL = 'CHEF_OWN_DETAILS_FAIL'
export const CHEF_OWN_REVIEWS_SUCCESS = 'CHEF_OWN_REVIEWS_SUCCESS'
export const CHEF_OWN_REVIEWS_FAIL = 'CHEF_OWN_REVIEWS_FAIL'
export const KITCHEN_DAILY_ORDERS_SUCCESS = 'KITCHEN_DAILY_ORDERS_SUCCESS'
export const KITCHEN_DAILY_ORDERS_FAIL = 'KITCHEN_DAILY_ORDERS_FAIL'
export const KITCHEN_MONTHLY_ORDERS_SUCCESS = 'KITCHEN_MONTHLY_ORDERS_SUCCESS'
export const KITCHEN_MONTHLY_ORDERS_FAIL = 'KITCHEN_MONTHLY_ORDERS_FAIL'
export const GET_KITCHEN_REVIEWS_SUCCESS = 'GET_KITCHEN_REVIEWS_SUCCESS'
export const GET_KITCHEN_REVIEWS_FAIL = 'GET_KITCHEN_REVIEWS_FAIL'
