export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS'
export const CUSTOMER_REGISTER_FAIL = 'CUSTOMER_REGISTER_FAIL'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const USER_LOADED = 'USER_LOADED'
export const CHEF_REGISTER_SUCCESS = 'CHEF_REGISTER_SUCCESS'
export const CHEF_REGISTER_FAIL = 'CHEF_REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const HISTORY_RECOMMENDATION_SUCCESS = 'HISTORY_RECOMMENDATION_SUCCESS'
export const HISTORY_RECOMMENDATION_FAIL = 'HISTORY_RECOMMENDATION_FAIL'

export const CHEF_EDITPROFILE_SUCCESS = 'CHEF_EDITPROFILE_SUCCESS'
export const CHEF_EDITPROFILE_FAIL = 'CHEF_EDITPROFILE_FAIL'
export const CHEF_PASSCHANGE_SUCCESS = 'CHEF_PASSCHANGE_SUCCESS'
export const CHEF_PASSCHANGE_FAIL = 'CHEF_PASSCHANGE_FAIL'

export const CUSTOMER_EDITPROFILE_SUCCESS = 'CUSTOMER_EDITPROFILE_SUCCESS'
export const CUSTOMER_EDITPROFILE_FAIL = 'CUSTOMER_EDITPROFILE_FAIL'
export const CUSTOMER_PASSCHANGE_SUCCESS = 'CUSTOMER_PASSCHANGE_SUCCESS'
export const CUSTOMER_PASSCHANGE_FAIL = 'CUSTOMER_PASSCHANGE_FAIL'


export const POPULAR_KITCHENS_SUCCESS = 'POPULAR_KITCHENS_SUCCESS'
export const POPULAR_KITCHENS_FAIL = 'POPULAR_KITCHENS_FAIL'

export const LOGOUT = 'LOGOUT'
export const ACTIVE_ORDERS_CHEF_SUCCESS = 'ACTIVE_ORDERS_CHEF_SUCCESS'
export const ACTIVE_ORDERS_CHEF_FAIL = 'ACTIVE_ORDERS_CHEF_FAIL'

export const COMPLETE_ORDERS_CHEF_SUCCESS = 'COMPLETE_ORDERS_CHEF_SUCCESS'
export const COMPLETE_ORDERS_CHEF_FAIL = 'COMPLETE_ORDERS_CHEF_FAIL'

export const ACTIVE_ORDERS_CUSTOMER_SUCCESS = 'ACTIVE_ORDERS_CUSTOMER_SUCCESS'
export const ACTIVE_ORDERS_CUSTOMER_FAIL = 'ACTIVE_ORDERS_CUSTOMER_FAIL'

export const COMPLETE_ORDERS_CUSTOMER_SUCCESS = 'COMPLETE_ORDERS_CUSTOMER_SUCCESS'
export const COMPLETE_ORDERS_CUSTOMER_FAIL = 'COMPLETE_ORDERS_CUSTOMER_FAIL'
export const ADD_CART = 'ADD_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const CHECKOUT_FAIL = "CHECKOUT_FAIL"
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS"
